# Full schema defined in /src/dpygt/config.py

[bot]
token = ""
extensions = [
    ".cogs.dice",
    ".cogs.owner",
]

[bot.intents]
# https://discordpy.readthedocs.io/en/stable/api.html#intents
# All default intents are enabled but can be modified here
# message_content = true
